version: 2

project_name: git-credentials-org

builds:
  - main: ./cmd/git-credentials-org
    binary: git-credentials-org
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: imcitius
    name: git-credentials-org

homebrew_casks:
  - name: git-credentials-org
    repository:
      owner: imcitius
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    directory: Casks
    commit_msg_template: "chore: update {{ .ProjectName }} to {{ .Tag }}"
    homepage: "https://github.com/imcitius/git-credentials-org"
    description: "Git credential helper that resolves credentials by organization namespace"
    license: "MIT"
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-credentials-org"]
